server:
  port: 8180
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/emobilink-registration
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
