server:
  port: 8180
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emobilink_registration
    username: emobilink
    password: LustigPeter
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update